systematics:
        rate:
                prior: 1e7
		sigma: 5e5
                low:  0.5e7
                high: 1.5e7
                step: 1e5
        parameters:
                energy:
                        resolution:
                                type: lightyield
                                prior: 200.
                                sigma: 5. 
                                min: 175.
                                max: 225.
                                step: 1.
                        scale:
                                prior: 1.
                                sigma: 0.01
                                min: 0.9
                                max: 1.1
                                step: 0.005
                        shift:
                                prior: 0.
                                sigma: 0.01
                                min: -0.1
                                max: 0.1
                                step: 0.005
